sudo: required
services: 
  - docker

before_install:
  - docker build -t eggyy1224/docker-react -f Dockerfile.dev .

script:
  - docker run eggyy1224/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-egg"
  env: "DockerReactEgg-env"
  bucket_name: "elasticbeanstalk-us-east-1-638139713801"
  bucket_path: "docker-react-egg"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"